name: CI Build and Release

on:
  push:
    branches:
      - "stage"

jobs:
  build:

    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          distribution: 'corretto'
          java-package: 'jdk+fx'
          java-version: '8'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.6

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/*.target') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Clean install
        run: mvn clean install -U
      - name: Build Application
        run: |
          mvn -U -V -e -B -ntp clean install compile package -pl client -amd -DskipTests
      - name: Build Updater
        run: |
          mvn -U -V -e -B -ntp clean install compile package -pl updater -amd -DskipTests
      - name: Upload Application
        uses: actions/upload-artifact@v3
        with:
          name: spicker
          path: D:\a\toolbox\toolbox\client\target\spicker.jar
      - name: Upload Updater
        uses: actions/upload-artifact@v3
        with:
          name: updater
          path: D:\a\toolbox\toolbox\updater\target\updater.jar

  pre-release:
    name: Pre Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Application
        uses: actions/download-artifact@v3
        with:
          name: spicker
      - name: Download Updater
        uses: actions/download-artifact@v3
        with:
          name: updater

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.jar